[package]

name = "websocket"
version = "0.17.2"
authors = ["cyderize <admin@cyderize.org>", "Michael Eden <themichaeleden@gmail.com>"]

description = "A WebSocket (RFC6455) library for Rust."

documentation = "http://cyderize.github.io/rust-websocket/doc/websocket/"
homepage = "http://cyderize.github.io/rust-websocket/"
repository = "https://github.com/cyderize/rust-websocket.git"

readme = "README.md"

keywords = ["websocket", "websockets", "rfc6455"]

license = "MIT"

[dependencies]
hyper = "^0.10"
unicase = "^1.0"
openssl = "^0.9.10"
url = "^1.0"
rustc-serialize = "^0.3"
bitflags = "^0.8"
rand = "^0.3"
byteorder = "^1.0"

[features]
nightly = ["hyper/nightly"]
