[package]

name = "websocket"
version = "0.9.5"
authors = ["cyderize <admin@cyderize.org>"]

description = "A WebSocket (RFC6455) library for Rust."

documentation = "http://cyderize.github.io/rust-websocket/doc/websocket/"
homepage = "http://cyderize.github.io/rust-websocket/"
repository = "https://github.com/cyderize/rust-websocket.git"

readme = "README.md"

keywords = ["websocket", "websockets", "rfc6455"]

license = "MIT"

[dependencies.sha1]
git = "https://github.com/cyderize/rust-sha1.git"
branch = "patch-1"

[dependencies.hyper]
git = "https://github.com/cyderize/hyper.git"
branch = "rustup"

[dependencies]
openssl = "~0.2.15"
url = "~0.2.16"
rustc-serialize = "~0.2.7"